server:
  port: 8091
    
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/e3-mall?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis: 
    host: 192.168.0.118
    password: foobareds
    port: 6379
    timeout: 5000 #连接超时时间（毫秒）
    jedis: 
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 2  #连接池中的最小空闲连接
  
#mybatis
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.e3mall.springboot.pojo #扫描实体类
  configuration: 
    mapUnderscoreToCamelCase: true #开启驼峰命名
    aggressiveLazyLoading: false #延迟加载
    lazyLoadingEnabled: true
    
dubbo:
  application: 
    name: e3-order #指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
  registry: 
    protocol: zookeeper #指定注册中心的位置
    address: 192.168.0.118:2181
  protocol: 
    name: dubbo #指定通信规则（通信协议？通信端口）
    port: 20885
  consumer: 
    # 关闭所有服务的启动时检查
    check: false

#redis中订单id的key
ORDER_ID_GEN_KEY: ORDER_ID_GEN
#redis中订单id初始值
ORDER_ID_START: 100544
ORDER_DETAIL_ID_GEN_KEY: ORDER_DETAIL_ID_GEN