server:
  port: 8081
  #servlet: 
    #context-path: /myblog

spring:
   mvc: 
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

file: 
  uploadUrl: http://192.168.0.144:88/blog #图片上传地址

dubbo:
  application:
    name: e3-manager-web #指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
  registry: 
    protocol: zookeeper #指定注册中心的位置
    address: 192.168.0.106:2181

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs: 
  so-timeout: 1501
  connect-timeout: 601 
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    #- 101.37.26.93:22122
    - 192.168.0.144:22122 

#图片服务器的地址
IMAGE_SERVER_URL: http://192.168.0.144:88/